language: c
sudo: required

services:
    - docker
notifications:
  email: false

install:
  - make -C fast.ai build && make -C fast.ai run
  - make -C latex-full build

before_install:
  - cd fast.ai && git clone --depth 1 https://github.com/fastai/fastai.git && cd -

script:
  - docker ps -a
  - cd latex-full && bash latexgen.sh main.tex && cd -
