language: c
sudo: required

services:
    - docker
notifications:
  email: false

install:
  - make -C fast.ai build && make -C fast.ai run
  - make -C Jekyll build && make -C Jekyll run

before_install:
  - cd fast.ai && git clone --depth 1 https://github.com/fastai/fastai.git && cd -
  - cd Jekyll && git clone --depth 1 https://github.com/mmphego/mmphego.github.io && cd -

script:
- docker ps -a
